### ISSUE TITLE
different websocket NPM modules in node-xmpp-server" and "node-xmpp-client"

### ISSUE THREAD

**Issue by aigninja** [node-xmpp/client#148]
Project "node-xmpp-server" and "node-xmpp-client" both have support for Websockets. 

"node-xmpp-server" provide websocket support through https://github.com/websockets/ws

"node-xmpp-client" provide websocket support through https://github.com/faye/faye-websocket-node

Can we use same webcoskets NPM module in in both

**Comment by sonnyp** [comment]
@aigninja I guess that would makes sense but I don't see an immediate benefit.

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/client/pull/200

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp/pull/305

**Comment by aigninja** [comment]
@sonnyp thanks :+1:
