### ISSUE TITLE
Client priority

### ISSUE THREAD

**Issue by Dyrk** [node-xmpp/client#202]
Is it possible to add `priority` field to the client parameters?
```var client = new Client( { priority : 50, ... } ); ```

Use case:
We have chat bot connected to xmpp server from different physical servers (to guarantee 100% uptime):
bot@xmpp_host/bot1
bot@xmpp_host/bot2
bot@xmpp_host/bot3

And when bot with resource "bot2" is down, XMPP server forward message both to /bot1 and /bot3. But only one chat bot should process incoming messages to avoid duplication. So they should be connected with the same jid, but unique resources and unique priorities (eg 10, 20, 30)

**Comment by sonnyp** [comment]
@Dyrk the priority is set when sending the presence stanza

https://xmpp.org/rfcs/rfc6121.html#presence-syntax-children-priority
