### ISSUE TITLE
DigestMD5 authentication issues on Node 6 + solution

### ISSUE THREAD

**Issue by robertklep** [node-xmpp/client#206]
A project of mine that uses `node-xmpp-client` is throwing XMPP authentication failures when using Node v6; with Node v4, the same code works just fine.

I tracked it down to [this line](https://github.com/node-xmpp/client/blob/b8c232634c7417c4d64aa6a87f9d8455daef0c4c/lib/authentication/digestmd5.js#L12); for Node v6, you need to explicitly provide an encoding of `binary`:

    hash.update(s, 'binary')

With this fix, my code works on both v4 and v6.

I'd be happy to provide a PR, but tests for the current repo are failing and adding my fix introduces more errors that seem to be related to `node-xmpp-server` (perhaps because of the same issue, idk).

**Comment by sonnyp** [comment]
What server do you use?

**Comment by robertklep** [comment]
External server over which I have no control :-( No idea what it's running, but I doubt it's Node.

However, the following demonstrates the difference between v4 and v6:
```
const crypto = require('crypto');
let hash     = crypto.createHash('md5');
console.log( hash.update('¶').digest('hex') );
```

On v4, the output is `da630c00d04be7f24cdaaacd01cf2e30`, on v6, the output is `7c5a057231e6f983c72b8b5461891a0c`.

**Comment by sonnyp** [comment]
Fails on Node.js 6 indeed https://travis-ci.org/node-xmpp/client/builds/131408382

Looks like a Node.js regression, could you open an issue there?

**Comment by robertklep** [comment]
It's not a regression but an API change.

[Node v4](https://nodejs.org/docs/latest-v4.x/api/crypto.html#crypto_hash_update_data_input_encoding): _"If encoding is not provided, and the data is a string, an encoding of 'binary' is enforced"_

[Node v6](https://nodejs.org/api/crypto.html#crypto_hash_update_data_input_encoding): _"If encoding is not provided, and the data is a string, an encoding of 'utf8' is enforced"_

**Comment by sonnyp** [comment]
Oh I missed that.

Fixing.

**Comment by sonnyp** [comment]
server: https://github.com/node-xmpp/server/pull/147

**Comment by sonnyp** [comment]
client: https://github.com/node-xmpp/client/pull/207

**Comment by sonnyp** [comment]
An other reason to switch to monorepo...

**Comment by sonnyp** [comment]
@robertklep done v3.0.1 please confirm the issue is fixed for you

**Comment by robertklep** [comment]
Yeah, that fixes it for me. Thanks! 😀

**Comment by sonnyp** [comment]
@robertklep thanks for the help

**Comment by sonnyp** [comment]
component: https://github.com/node-xmpp/component/pull/45
